export const API_ERROR_CODES = {
    VALIDATION_FAILED: "VALIDATION_FAILED",
    INVALID_USER_DATA: "INVALID_USER_DATA",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    RULE_ALREADY_EXISTS: "RULE_ALREADY_EXISTS",
    RULE_NOT_FOUND: "RULE_NOT_FOUND",
    RULE_ALREADY_ASSIGNED: "RULE_ALREADY_ASSIGNED",
    RULE_ASSIGNMENT_NOT_FOUND: "RULE_ASSIGNMENT_NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
export const VALIDATION_DETAIL_CODES = {
    REQUIRED: "REQUIRED",
    INVALID_EMAIL: "INVALID_EMAIL",
    MIN_LENGTH: "MIN_LENGTH",
    INVALID_TYPE: "INVALID_TYPE",
};
export function buildApiError(code, message, details) {
    return {
        error: {
            code,
            message,
            ...(details?.length ? { details } : {}),
        },
    };
}
